apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-error
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app-error
  template:
    metadata:
      labels:
        app: web-app-error
    spec:
      containers:
      - name: web-app-error
        image: ngnix:1.19.3
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10          